//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyUKRaine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translate
    {
        public int TID { get; set; }
        public int WID { get; set; }
        public string Translate1 { get; set; }
        public string ImageLink { get; set; }
    }
}
