//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyUKRaine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int InfoID { get; set; }
        public int UsID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> DateOfReg { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Country { get; set; }
        public string Location { get; set; }
        public string E_mail { get; set; }
    }
}
