//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyUKRaine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserHistory
    {
        public int HID { get; set; }
        public int UsID { get; set; }
        public Nullable<int> TopicID { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<int> Progress { get; set; }
        public string Info { get; set; }
    }
}
